// src/finlandLocations.js

const finlandLocations = [
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyväskylä",
    "Lahti",
    "Kuopio",
    "Kouvola",
    "Pori",
    "Joensuu",
    "Lappeenranta",
    "Vaasa",
    "Seinäjoki",
    "Rovaniemi",
    "Mikkeli",
    "Kotka",
    "Salo",
    "Porvoo",
    "Hyvinkää",
    "Kajaani",
    "Loviisa",
    "Rauma",
    "Lohja",
    "Kokkola",
    "Kemi",
    "Savonlinna",
    "Iisalmi",
    "Alajärvi",
    "Raasepori",
    "Nurmijärvi",
    "Raikka",
    "Kärsämäki",
    "Siilinjärvi",
    "Karstula",
    "Kitee",
    "Kontiolahti",
    "Sotkamo",
    "Savukoski",
    "Lapinjärvi",
    "Sodankylä",
    "Enonkoski",
    "Kangasala",
    "Ruokolahti",
    "Kankaanpää",
    "Kangasniemi",
    "Uusikaupunki",
    "Orimattila",
    "Sastamala",
    "Kivijärvi",
    "Raisio",
    "Valkeakoski",
    "Varkaus",
    "Paimio",
    "Riihimäki",
    "Äänekoski",
    "Vesilahti",
    "Sipoo",
    "Lapua",
    // Add more locations as needed
  ];
  
  export default finlandLocations;
  