name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - ux-review  # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: ux-review  # Replace with your branch name
          folder: build
